name: dot_matrix_widget
description: "Render any widget as a customizable dot-matrix display in Flutter."
version: 0.1.1
homepage: https://github.com/topmoveright/dot_matrix_widget


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

topics:
  - dot
  - widgets
  - graphics
  - animation

screenshots:
  - description: Dot matrix preview of the included demo
    path: example/assets/example.png

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
